Repository crate/crate-admin, pull requests merged in 2020-07, with the labels that each got.

#678 Upgrade to docs build 0.3.1
  .gitignore
  .readthedocs.yml
  DEVELOP.rst
  docs/Makefile
  docs/build.json
Labels: documentation, meta

#680 Add HTML build to config
  .readthedocs.yml
Labels: bug, documentation

#681 Fix typos in tweet import doc
  docs/help.rst
Labels: area: docs, content: copyedit, scope: trivial, team: tech writing
