Repository crate/crate-admin, pull requests merged in 2024-01, with the labels that each got.

#828 Optimize pics
  docs/_assets/img/admin-ui.png
  docs/_assets/img/cluster.png
  docs/_assets/img/console-default.png
  docs/_assets/img/console-query.png
  docs/_assets/img/help.png
  docs/_assets/img/monitoring.png
  docs/_assets/img/privileges-superuser.png
  docs/_assets/img/privileges-user.png
  docs/_assets/img/shards.png
  docs/_assets/img/tables.png
  docs/_assets/img/views.png
Labels: docs

#831 Tests: Use Chromium instead of PhantomJS with Karma testing
  karma.conf.js
  package-lock.json
  package.json
Labels: enhancement, dependencies

#833 Sandbox: Update to Node.js 20 and NPM 10
  .github/workflows/tests.yml
  bootstrap.sh
Labels: dependencies

#836 Sandbox: Update development docs about changes to the release process
  DEVELOP.rst
Labels: docs

#832 Dependencies: Another wave of updates provided by `npm audit fix`
  package-lock.json
Labels: dependencies
